//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaidHex.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaidHex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 无
        ///普通(红)
        ///稀有(紫)
        ///许愿星块普通(红)
        ///许愿星块稀有(紫)
        ///活动
        ///极巨结晶 的本地化字符串。
        /// </summary>
        internal static string denType_zh {
            get {
                return ResourceManager.GetString("denType_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 牙牙湖之眼
        ///桥间空地
        ///沐光森林
        ///沙尘洼地
        ///牙牙湖东岸
        ///巨人帽岩
        ///巨人镜池
        ///巨人凳岩
        ///拳关丘陵
        ///逆鳞湖
        ///机擎河岸
        ///美纳斯湖北岸
        ///煦丽草原
        ///美纳斯湖南岸
        ///巨石原野
        ///瞭望塔旧址
        ///牙牙湖西岸
        ///揖礼原野
        ///清凉湿原
        ///专注森林
        ///挑战海滩
        ///战斗洞窟
        ///挑战之路
        ///斗志洞窟
        ///圆环海湾
        ///锻炼平原
        ///锅底沙漠
        ///健身之海
        ///列岛海域
        ///离岛海域
        ///蜂巢海
        ///蜂巢岛 的本地化字符串。
        /// </summary>
        internal static string locations_zh {
            get {
                return ResourceManager.GetString("locations_zh", resourceCulture);
            }
        }
    }
}
